# Converted matrix_gui.ui to python code for implementation
# Created by: Radhakrishnan Ramanujam

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MatrixGui(object):
    def setupUi(self, MatrixGui):
        MatrixGui.setObjectName("MatrixGui")
        self.verticalLayout = QtWidgets.QVBoxLayout(MatrixGui)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputGroupBox = QtWidgets.QGroupBox(parent=MatrixGui)
        self.inputGroupBox.setObjectName("inputGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.inputGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.labelRows = QtWidgets.QLabel(parent=self.inputGroupBox)
        self.labelRows.setObjectName("labelRows")
        self.gridLayout.addWidget(self.labelRows, 0, 0, 1, 1)
        self.rowSpinBox = QtWidgets.QSpinBox(parent=self.inputGroupBox)
        self.rowSpinBox.setObjectName("rowSpinBox")
        self.gridLayout.addWidget(self.rowSpinBox, 0, 1, 1, 1)
        self.labelCols = QtWidgets.QLabel(parent=self.inputGroupBox)
        self.labelCols.setObjectName("labelCols")
        self.gridLayout.addWidget(self.labelCols, 0, 2, 1, 1)
        self.colSpinBox = QtWidgets.QSpinBox(parent=self.inputGroupBox)
        self.colSpinBox.setObjectName("colSpinBox")
        self.gridLayout.addWidget(self.colSpinBox, 0, 3, 1, 1)
        self.matrixTable = QtWidgets.QTableWidget(parent=self.inputGroupBox)
        self.matrixTable.setObjectName("matrixTable")
        self.matrixTable.setColumnCount(0)
        self.matrixTable.setRowCount(0)
        self.gridLayout.addWidget(self.matrixTable, 1, 0, 1, 4)
        self.computeButton = QtWidgets.QPushButton(parent=self.inputGroupBox)
        self.computeButton.setObjectName("computeButton")
        self.gridLayout.addWidget(self.computeButton, 2, 0, 1, 2)
        self.orthogonalityButton = QtWidgets.QPushButton(parent=self.inputGroupBox)
        self.orthogonalityButton.setObjectName("orthogonalityButton")
        self.gridLayout.addWidget(self.orthogonalityButton, 2, 2, 1, 2)
        self.verticalLayout.addWidget(self.inputGroupBox)
        self.resultsTabs = QtWidgets.QTabWidget(parent=MatrixGui)
        self.resultsTabs.setObjectName("resultsTabs")
        self.tabDiagonalization = QtWidgets.QWidget()
        self.tabDiagonalization.setObjectName("tabDiagonalization")
        self.verticalLayoutTab1 = QtWidgets.QVBoxLayout(self.tabDiagonalization)
        self.verticalLayoutTab1.setObjectName("verticalLayoutTab1")
        self.diagStatusLabel = QtWidgets.QLabel(parent=self.tabDiagonalization)
        self.diagStatusLabel.setObjectName("diagStatusLabel")
        self.verticalLayoutTab1.addWidget(self.diagStatusLabel)
        self.labelDiagMatrix = QtWidgets.QLabel(parent=self.tabDiagonalization)
        self.labelDiagMatrix.setObjectName("labelDiagMatrix")
        self.verticalLayoutTab1.addWidget(self.labelDiagMatrix)
        self.diagMatrixTable = QtWidgets.QTableWidget(parent=self.tabDiagonalization)
        self.diagMatrixTable.setObjectName("diagMatrixTable")
        self.diagMatrixTable.setColumnCount(0)
        self.diagMatrixTable.setRowCount(0)
        self.verticalLayoutTab1.addWidget(self.diagMatrixTable)
        self.labelTransformMatrix = QtWidgets.QLabel(parent=self.tabDiagonalization)
        self.labelTransformMatrix.setObjectName("labelTransformMatrix")
        self.verticalLayoutTab1.addWidget(self.labelTransformMatrix)
        self.transformMatrixTable = QtWidgets.QTableWidget(parent=self.tabDiagonalization)
        self.transformMatrixTable.setObjectName("transformMatrixTable")
        self.transformMatrixTable.setColumnCount(0)
        self.transformMatrixTable.setRowCount(0)
        self.verticalLayoutTab1.addWidget(self.transformMatrixTable)
        self.resultsTabs.addTab(self.tabDiagonalization, "")
        self.tabOrthogonality = QtWidgets.QWidget()
        self.tabOrthogonality.setObjectName("tabOrthogonality")
        self.verticalLayoutTab2 = QtWidgets.QVBoxLayout(self.tabOrthogonality)
        self.verticalLayoutTab2.setObjectName("verticalLayoutTab2")
        self.orthoStatusLabel = QtWidgets.QLabel(parent=self.tabOrthogonality)
        self.orthoStatusLabel.setObjectName("orthoStatusLabel")
        self.verticalLayoutTab2.addWidget(self.orthoStatusLabel)
        self.labelOrthoProduct = QtWidgets.QLabel(parent=self.tabOrthogonality)
        self.labelOrthoProduct.setObjectName("labelOrthoProduct")
        self.verticalLayoutTab2.addWidget(self.labelOrthoProduct)
        self.orthoProductTable = QtWidgets.QTableWidget(parent=self.tabOrthogonality)
        self.orthoProductTable.setObjectName("orthoProductTable")
        self.orthoProductTable.setColumnCount(0)
        self.orthoProductTable.setRowCount(0)
        self.verticalLayoutTab2.addWidget(self.orthoProductTable)
        self.resultsTabs.addTab(self.tabOrthogonality, "")
        self.verticalLayout.addWidget(self.resultsTabs)
        self.bottomButtonLayout = QtWidgets.QHBoxLayout()
        self.bottomButtonLayout.setObjectName("bottomButtonLayout")
        self.clearButton = QtWidgets.QPushButton(parent=MatrixGui)
        self.clearButton.setObjectName("clearButton")
        self.bottomButtonLayout.addWidget(self.clearButton)
        self.exportButton = QtWidgets.QPushButton(parent=MatrixGui)
        self.exportButton.setObjectName("exportButton")
        self.bottomButtonLayout.addWidget(self.exportButton)
        self.glossaryButton = QtWidgets.QPushButton(parent=MatrixGui) # Change this to glossary button!
        self.glossaryButton.setObjectName("glossaryButton")
        self.bottomButtonLayout.addWidget(self.glossaryButton)
        self.verticalLayout.addLayout(self.bottomButtonLayout)

        self.retranslateUi(MatrixGui)
        QtCore.QMetaObject.connectSlotsByName(MatrixGui)

    def retranslateUi(self, MatrixGui):
        _translate = QtCore.QCoreApplication.translate
        MatrixGui.setWindowTitle(_translate("MatrixGui", "Matrix Diagonalization and Orthogonality Checker"))
        self.inputGroupBox.setTitle(_translate("MatrixGui", "Matrix Input"))
        self.labelRows.setText(_translate("MatrixGui", "Rows:"))
        self.labelCols.setText(_translate("MatrixGui", "Columns:"))
        self.computeButton.setText(_translate("MatrixGui", "Compute Diagonalization"))
        self.orthogonalityButton.setText(_translate("MatrixGui", "Check Orthogonality"))
        self.diagStatusLabel.setText(_translate("MatrixGui", "Diagonalization Status"))
        self.labelDiagMatrix.setText(_translate("MatrixGui", "Diagonalized Matrix:"))
        self.labelTransformMatrix.setText(_translate("MatrixGui", "Transformation Matrix:"))
        self.resultsTabs.setTabText(self.resultsTabs.indexOf(self.tabDiagonalization), _translate("MatrixGui", "Diagonalization Result"))
        self.orthoStatusLabel.setText(_translate("MatrixGui", "Orthogonality Status"))
        self.labelOrthoProduct.setText(_translate("MatrixGui", "Matrix × Transpose:"))
        self.resultsTabs.setTabText(self.resultsTabs.indexOf(self.tabOrthogonality), _translate("MatrixGui", "Orthogonality Check"))
        self.clearButton.setText(_translate("MatrixGui", "Clear"))
        self.exportButton.setText(_translate("MatrixGui", "Export Results"))
        self.glossaryButton.setText(_translate("MatrixGui", "Glossary"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MatrixGui = QtWidgets.QWidget()
    ui = Ui_MatrixGui()
    ui.setupUi(MatrixGui)
    MatrixGui.show()
    sys.exit(app.exec())
