project(
  'elliptic_curves',
  version: '0.8.1',
  meson_version: '>=1.5',
)

elliptic_curves_generator = files('generate.py')[0]
elliptic_curves_allcurves = files('common/allcurves.00000-09999')[0]
elliptic_curves_rank_sources = files(
  'ellcurves/rank3',
  'ellcurves/rank4',
  'ellcurves/rank5',
  'ellcurves/rank6',
  'ellcurves/rank7',
  'ellcurves/rank8',
  'ellcurves/rank9',
  'ellcurves/rank10',
  'ellcurves/rank11',
  'ellcurves/rank12',
  'ellcurves/rank14',
  'ellcurves/rank15',
  'ellcurves/rank17',
  'ellcurves/rank19',
  'ellcurves/rank20',
  'ellcurves/rank21',
  'ellcurves/rank22',
  'ellcurves/rank23',
  'ellcurves/rank24',
  'ellcurves/rank28',
)
elliptic_curves_rank_outputs = [
  'rank0',
  'rank1',
  'rank2',
  'rank3',
  'rank4',
  'rank5',
  'rank6',
  'rank7',
  'rank8',
  'rank9',
  'rank10',
  'rank11',
  'rank12',
  'rank14',
  'rank15',
  'rank17',
  'rank19',
  'rank20',
  'rank21',
  'rank22',
  'rank23',
  'rank24',
  'rank28',
]
