mapBanner = """
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd,xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMN00WMMMMMMMMMMM0:cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMM0d0MMMMMMMMMMM0oOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWNNNNWMMMNOOk0WMMMMMMMMMXo:kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMW0o:o00xOx,.;l0WMMMMMMMWkoONMMMMMMNKKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWKc.;OXo..  .cKMMMMMMMMWXNMMMMMMMMNddXWWMWXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXWWXKNWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWKdlcdXM0;';'.;OWMMMMMMMWWWMMMMMMMMWdlxOXM0oOWWMMMMMMMMMMMMMMMMMMMMMMMMMMM0c;ll:oKWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMNK0xckNK:;oo'.,d00KXNWWK0NMMMMMMMMWKkclKNkxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,.;dONMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWWXOx:.'c;..'. ..'..',;:c;,kNMMMMMMMMNXxcodxXMMNKXWMMMMMMMMKKWMMMMMMMMMMWKd;cOXMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMWXXXKXXKOoclc'.........   .....'...'dKWMMMMMMMMN0l',,oNNXkdKWMMMMMMMMXKWMMMMMMMMWXk;.,kWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMW0OKKOo;;;;,...,cc:,..........;;;,cONMMMMMMMN0Okc...'lkO0KNMMMMMMMMMWNXNWWMWXXWMNd',dKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMW0kKN0ddxOKNWNKd,.......';::;lKMMMMMNXKx,....'.'':kKXWMMMMMMMMMKxloxdoc,c0NOco0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWNWMMMMMMWKOx:.  ..,:::::xNMMMMWkc,.  ...','':cdKWMMMMMMMMXc..,'....:cckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWk;'...';:::;:xNMMMWk,.........'cO0KNWMMMMXKXX0c..';,'',;;oNMWWWMMMMMMMMMMMMMMMMMMMMMMMMMWNWMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMNN0; ..':::;::lk000o...........lKNWMMMMMMOcdd:,'',,;;;,,'ckO0KNMMMMMMMMMMMMMMMMMMMMMMMWM0cdNM
MMMMMMMMMMMMMMMMMMMMMMWWWWK0XXk;...',,,'''''..... ....,,'',:co0NWWWNO:;c:;;:;;;;,,'..:dOKWMMMMMMMMMWKKWMMMMMMMX0Oddc':kX
MMMMMMMMMMMMMMMMMMMMMMNXKKx:cxkl'........','.....   .',;;;,,,,:dkdoolclollllc,.......:kOKWMMMMMMMMMXdd0xOWMWMWx,,,'l0XNW
MMMMMMMMMMMMMMMMMMMMMMMMWXXXXNNd..........'''.......';;;;;;;;;,,',coddoooddo:,,;;.. .oKWMMMMMMMMMWXk;..,kNOldxdk0KKXWMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWMWX0d,.'.....  ............,::::::c:'..;loooollooolllc:;,;;cxKWMMMMMMMMM0:...,lollllxXMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMNkc....'....       .. ......',::,,,,,;::lolloolllclool:l0NNNXNMMMMMMMWNO:..;odddOXNNXNMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWx'  .....'codxxo,.......'''''',,,,;:cc:;',:llccllcllllllok0NMMMMMMMWNO:.':dKWMWNWMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWNKx:.......'oKWMMMMW0xkOO:...'',::,,;,..,;;;,'',;:llccll:;:::,;lkKNWNKko:,';dXWMWNXWMMMMMMMMMMMMMM
MMMMMMMMMMMWKKKOxkKXKkl'.........,0MMMMMMMMWNOd;.....':cc:,.....',,;;;',:,',:oo::dkl,',;:cc;..'l0XNWNKkoOWMMMMMMMMMMMMMM
MMMMMMMMMWNNKkko...,;:;. ......cc,kWMMMMMWXOOd'   ....;:::,......'.',;,'..;d0NW0olOXkxkkxl,..,;kWMMXdlOXWMMMMMMMMMMMMMMM
MMMMMMMMXd:co,''.,ldON0;..:kKxoOko0MMMMWKd:''... .....;:::;'.. .....',,'':xXMMMW0ll0WMMMMXl...,dOKKl'dWMMMMMMMMMMMMMMMMM
MMMMMMMWk'.'odxkokNMMWx'.lXMMWNWWXWMMMMMNx;.,lc.    ..;:'','..  ...',,,,dNNNWMMMMW0ONMMMMNOc'...'',.,kNMMMMMMMMMMMMMMMMM
MMMMMMMWKdxKWMMMWWMMM0,.'dXMMMMMMMMMMMMMMKxxOOd;..  ..''............'.';dXWMMMMMMMMMMMMMMMXd'..     .,coxOKNMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMXx;'lOXMMMMMMMMMMMMMMMWNK0Oxxxoc:,.....'.....'...';cdKWMMMMMMMMMMMMMMMNOdc:'... ...,okk0XNWMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMNXO:oNMMMMMMMMMMMMMMMMMWKddXMMWNXOxl,cOK0Oc..''',:xOOXMMMMMMMMMMMMMMMMMMWN0:.......cXMMWMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWXNMMMMMMMMMMMMMMMXOxl,'xWMMMMWMXllXMMMWO;,:;,..cKMMMMMMMMMMMMMMMMMMMMMWKl'......;0MMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKx,.lXMMMMMMXOkXMMMMMKk0NOo,.,kWMMMMMMMMMMMMMMMMMMMMNXX0d:,...'l0NMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdc0MMMMMMMNNWMMMMMMWWMWXXd',dNMMMMMMMMMMMMMMMMMMMMWWMMWXKkoc,,dKNWMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxdKMMMMMMMMMMMMMMMMMMMMMNd'.,kWMMMMMMMMMMMMMMMMMMMMMMMMMMWWXkkXNXWMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOOXNMMMMMMMMMMMMMMMMMMMMMNx'.,dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMWXk:'cONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMOcoOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWOOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKodXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX0koOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOoONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdlONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
"""


bannerExampleStart = """
#     #                         #######                                                  
##   ##   ##   #####   ####     #       #    #   ##   #    # #####  #      ######  ####  
# # # #  #  #  #    # #         #        #  #   #  #  ##  ## #    # #      #      #      
#  #  # #    # #    #  ####     #####     ##   #    # # ## # #    # #      #####   ####  
#     # ###### #####       #    #         ##   ###### #    # #####  #      #           # 
#     # #    # #      #    #    #        #  #  #    # #    # #      #      #      #    # 
#     # #    # #       ####     ####### #    # #    # #    # #      ###### ######  ####  
"""

bannerExampleEnd = """
#######                                                       ###
   #    #    #   ##   #    # #    #    #   #  ####  #    #    ###
   #    #    #  #  #  ##   # #   #      # #  #    # #    #    ###
   #    ###### #    # # #  # ####        #   #    # #    #     #
   #    #    # ###### #  # # #  #        #   #    # #    #
   #    #    # #    # #   ## #   #       #   #    # #    #    ###
   #    #    # #    # #    # #    #      #    ####   ####     ###
                                                                  
"""
