# TODO: Move to pyproject.toml once https://github.com/tamasfe/taplo/issues/603 is fixed

[formatting]
# https://taplo.tamasfe.dev/configuration/formatter-options.html
align_comments = false
align_entries = false
array_auto_collapse = false
reorder_arrays = true
reorder_inline_tables = true
reorder_keys = true
