#! /bin/sh

# Note: ./configure will remove all conftest* files, including the
# pytest conftest.py. We work around this by making a copy and
# restoring when we are done, regardless of whether configure succeeds
# or fails.
# The backup file must NOT start with "conftest" to avoid being deleted
# by the "rm -rf conftest*" commands in the configure script.

set -e

trap 'mv .backup_conftest.py conftest.py; trap - EXIT; exit' EXIT INT HUP TERM

cp conftest.py .backup_conftest.py
./real_configure $@
