# Sage version information for Python scripts
# This file is auto-generated by the sage-update-version script, do not edit!
version = '10.3.beta5'
date = '2024-01-14'
banner = 'SageMath version 10.3.beta5, Release Date: 2024-01-14'
