# Sage version information for Python scripts
# This file is auto-generated by the update-version script, do not edit!
version = '10.10.beta9'
date = '2026-08-23'
banner = 'SageMath version 10.10.beta9, Release Date: 2026-08-23'
