py.install_sources(
    'all.py',
    'circuit_oriented_matroid.py',
    'covector_oriented_matroid.py',
    'oriented_matroid.py',
    'real_hyperplane_arrangement_oriented_matroid.py',
    'signed_subset_element.py',
    'vector_oriented_matroid.py',
  subdir: 'sage/matroids/oriented_matroids',
)
