# distutils: libraries = flint
# distutils: depends = flint/double_extras.h

################################################################################
# This file is auto-generated by the script
#   tools/autogen/flint_autogen.py.
# From the commit 0915468d82ae2df8bacf6df7eb95347d6a0554b9
# Do not modify by hand! Fix and rerun the script instead.
################################################################################

from libc.stdio cimport FILE
from sage.libs.gmp.types cimport *
from sage.libs.mpfr.types cimport *
from sage.libs.flint.types cimport *

cdef extern from "flint_wrap.h":
    double d_randtest(flint_rand_t state) noexcept
    double d_randtest_signed(flint_rand_t state, slong minexp, slong maxexp) noexcept
    double d_randtest_special(flint_rand_t state, slong minexp, slong maxexp) noexcept
    double d_polyval(const double * poly, int len, double x) noexcept
    double d_mul_2exp_inrange(double x, int i) noexcept
    double d_mul_2exp_inrange2(double x, int i) noexcept
    double d_mul_2exp(double x, int i) noexcept
    double d_lambertw(double x) noexcept
    bint d_is_nan(double x) noexcept
    double d_log2(double x) noexcept
