# distutils: libraries = flint
# distutils: depends = flint/long_extras.h

################################################################################
# This file is auto-generated by the script
#   SAGE_ROOT/tools/flint-autogen/flint_autogen.py.
# From the commit 1579f63c21cc8f1377e55da808ee2b8acb958233
# Do not modify by hand! Fix and rerun the script instead.
################################################################################

from libc.stdio cimport FILE
from sage.libs.gmp.types cimport *
from sage.libs.mpfr.types cimport *
from sage.libs.flint.types cimport *

cdef extern from "flint_wrap.h":
    size_t z_sizeinbase(slong n, int b) noexcept
    int z_mul_checked(slong * a, slong b, slong c) noexcept
    slong z_randtest(flint_rand_t state) noexcept
    slong z_randtest_not_zero(flint_rand_t state) noexcept
    slong z_randint(flint_rand_t state, ulong limit) noexcept
    int z_kronecker(slong a, slong n) noexcept
