# distutils: libraries = flint
# distutils: depends = flint/nf.h

################################################################################
# This file is auto-generated by the script
#   tools/autogen/flint_autogen.py.
# From the commit 0915468d82ae2df8bacf6df7eb95347d6a0554b9
# Do not modify by hand! Fix and rerun the script instead.
################################################################################

from libc.stdio cimport FILE
from sage.libs.gmp.types cimport *
from sage.libs.mpfr.types cimport *
from sage.libs.flint.types cimport *

cdef extern from "flint_wrap.h":
    void nf_init(nf_t nf, const fmpq_poly_t pol) noexcept
    void nf_clear(nf_t nf) noexcept
