# distutils: libraries = flint
# distutils: depends = flint/nmod.h

################################################################################
# This file is auto-generated by the script
#   tools/autogen/flint_autogen.py.
# From the commit 0915468d82ae2df8bacf6df7eb95347d6a0554b9
# Do not modify by hand! Fix and rerun the script instead.
################################################################################

from libc.stdio cimport FILE
from sage.libs.gmp.types cimport *
from sage.libs.mpfr.types cimport *
from sage.libs.flint.types cimport *

cdef extern from "flint_wrap.h":
    void nmod_init(nmod_t * mod, ulong n) noexcept
    ulong _nmod_add(ulong a, ulong b, nmod_t mod) noexcept
    ulong nmod_add(ulong a, ulong b, nmod_t mod) noexcept
    ulong _nmod_sub(ulong a, ulong b, nmod_t mod) noexcept
    ulong nmod_sub(ulong a, ulong b, nmod_t mod) noexcept
    ulong nmod_neg(ulong a, nmod_t mod) noexcept
    ulong nmod_mul(ulong a, ulong b, nmod_t mod) noexcept
    ulong _nmod_mul_fullword(ulong a, ulong b, nmod_t mod) noexcept
    ulong nmod_inv(ulong a, nmod_t mod) noexcept
    ulong nmod_div(ulong a, ulong b, nmod_t mod) noexcept
    int nmod_divides(ulong * a, ulong b, ulong c, nmod_t mod) noexcept
    ulong nmod_pow_ui(ulong a, ulong e, nmod_t mod) noexcept
    ulong nmod_pow_fmpz(ulong a, const fmpz_t e, nmod_t mod) noexcept
    void nmod_discrete_log_pohlig_hellman_init(nmod_discrete_log_pohlig_hellman_t L) noexcept
    void nmod_discrete_log_pohlig_hellman_clear(nmod_discrete_log_pohlig_hellman_t L) noexcept
    double nmod_discrete_log_pohlig_hellman_precompute_prime(nmod_discrete_log_pohlig_hellman_t L, ulong p) noexcept
    ulong nmod_discrete_log_pohlig_hellman_primitive_root(const nmod_discrete_log_pohlig_hellman_t L) noexcept
    ulong nmod_discrete_log_pohlig_hellman_run(const nmod_discrete_log_pohlig_hellman_t L, ulong y) noexcept
