from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MatrixGui(object):
    def setupUi(self, MatrixGui):
        MatrixGui.setObjectName("MatrixGui")
        self.verticalLayout = QtWidgets.QVBoxLayout(MatrixGui)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputGroupBox = QtWidgets.QGroupBox(MatrixGui)
        self.inputGroupBox.setObjectName("inputGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.inputGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.labelRows = QtWidgets.QLabel(self.inputGroupBox)
        self.labelRows.setObjectName("labelRows")
        self.gridLayout.addWidget(self.labelRows, 0, 0, 1, 1)
        self.rowSpinBox = QtWidgets.QSpinBox(self.inputGroupBox)
        self.rowSpinBox.setObjectName("rowSpinBox")
        self.gridLayout.addWidget(self.rowSpinBox, 0, 1, 1, 1)
        self.labelCols = QtWidgets.QLabel(self.inputGroupBox)
        self.labelCols.setObjectName("labelCols")
        self.gridLayout.addWidget(self.labelCols, 0, 2, 1, 1)
        self.colSpinBox = QtWidgets.QSpinBox(self.inputGroupBox)
        self.colSpinBox.setObjectName("colSpinBox")
        self.gridLayout.addWidget(self.colSpinBox, 0, 3, 1, 1)
        self.matrixTable = QtWidgets.QTableWidget(self.inputGroupBox)
        self.matrixTable.setObjectName("matrixTable")
        self.matrixTable.setColumnCount(0)
        self.matrixTable.setRowCount(0)
        self.gridLayout.addWidget(self.matrixTable, 1, 0, 1, 4)
        self.computeButton = QtWidgets.QPushButton(self.inputGroupBox)
        self.computeButton.setObjectName("computeButton")
        self.gridLayout.addWidget(self.computeButton, 2, 0, 1, 1)
        self.orthogonalityButton = QtWidgets.QPushButton(self.inputGroupBox)
        self.orthogonalityButton.setObjectName("orthogonalityButton")
        self.gridLayout.addWidget(self.orthogonalityButton, 2, 1, 1, 1)
        self.svdButton = QtWidgets.QPushButton(self.inputGroupBox)
        self.svdButton.setObjectName("svdButton")
        self.gridLayout.addWidget(self.svdButton, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.inputGroupBox)
        self.resultsTabs = QtWidgets.QTabWidget(MatrixGui)
        self.resultsTabs.setObjectName("resultsTabs")
        self.tabDiagonalization = QtWidgets.QWidget()
        self.tabDiagonalization.setObjectName("tabDiagonalization")
        self.verticalLayoutTab1 = QtWidgets.QVBoxLayout(self.tabDiagonalization)
        self.verticalLayoutTab1.setObjectName("verticalLayoutTab1")
        self.diagStatusLabel = QtWidgets.QLabel(self.tabDiagonalization)
        self.diagStatusLabel.setObjectName("diagStatusLabel")
        self.verticalLayoutTab1.addWidget(self.diagStatusLabel)
        self.labelDiagMatrix = QtWidgets.QLabel(self.tabDiagonalization)
        self.labelDiagMatrix.setObjectName("labelDiagMatrix")
        self.verticalLayoutTab1.addWidget(self.labelDiagMatrix)
        self.diagMatrixTable = QtWidgets.QTableWidget(self.tabDiagonalization)
        self.diagMatrixTable.setObjectName("diagMatrixTable")
        self.diagMatrixTable.setColumnCount(0)
        self.diagMatrixTable.setRowCount(0)
        self.verticalLayoutTab1.addWidget(self.diagMatrixTable)
        self.labelTransformMatrix = QtWidgets.QLabel(self.tabDiagonalization)
        self.labelTransformMatrix.setObjectName("labelTransformMatrix")
        self.verticalLayoutTab1.addWidget(self.labelTransformMatrix)
        self.transformMatrixTable = QtWidgets.QTableWidget(self.tabDiagonalization)
        self.transformMatrixTable.setObjectName("transformMatrixTable")
        self.transformMatrixTable.setColumnCount(0)
        self.transformMatrixTable.setRowCount(0)
        self.verticalLayoutTab1.addWidget(self.transformMatrixTable)
        self.resultsTabs.addTab(self.tabDiagonalization, "")
        self.tabOrthogonality = QtWidgets.QWidget()
        self.tabOrthogonality.setObjectName("tabOrthogonality")
        self.verticalLayoutTab2 = QtWidgets.QVBoxLayout(self.tabOrthogonality)
        self.verticalLayoutTab2.setObjectName("verticalLayoutTab2")
        self.orthoStatusLabel = QtWidgets.QLabel(self.tabOrthogonality)
        self.orthoStatusLabel.setObjectName("orthoStatusLabel")
        self.verticalLayoutTab2.addWidget(self.orthoStatusLabel)
        self.labelOrthoProduct = QtWidgets.QLabel(self.tabOrthogonality)
        self.labelOrthoProduct.setObjectName("labelOrthoProduct")
        self.verticalLayoutTab2.addWidget(self.labelOrthoProduct)
        self.orthoProductTable = QtWidgets.QTableWidget(self.tabOrthogonality)
        self.orthoProductTable.setObjectName("orthoProductTable")
        self.orthoProductTable.setColumnCount(0)
        self.orthoProductTable.setRowCount(0)
        self.verticalLayoutTab2.addWidget(self.orthoProductTable)
        self.resultsTabs.addTab(self.tabOrthogonality, "")
        self.tabSVD = QtWidgets.QWidget()
        self.tabSVD.setObjectName("tabSVD")
        self.verticalLayoutTab3 = QtWidgets.QVBoxLayout(self.tabSVD)
        self.verticalLayoutTab3.setObjectName("verticalLayoutTab3")
        self.svdULabel = QtWidgets.QLabel(self.tabSVD)
        self.svdULabel.setObjectName("svdULabel")
        self.verticalLayoutTab3.addWidget(self.svdULabel)
        self.svdUTable = QtWidgets.QTableWidget(self.tabSVD)
        self.svdUTable.setObjectName("svdUTable")
        self.svdUTable.setColumnCount(0)
        self.svdUTable.setRowCount(0)
        self.verticalLayoutTab3.addWidget(self.svdUTable)
        self.svdSLabel = QtWidgets.QLabel(self.tabSVD)
        self.svdSLabel.setObjectName("svdSLabel")
        self.verticalLayoutTab3.addWidget(self.svdSLabel)
        self.svdSTable = QtWidgets.QTableWidget(self.tabSVD)
        self.svdSTable.setObjectName("svdSTable")
        self.svdSTable.setColumnCount(0)
        self.svdSTable.setRowCount(0)
        self.verticalLayoutTab3.addWidget(self.svdSTable)
        self.svdVTLabel = QtWidgets.QLabel(self.tabSVD)
        self.svdVTLabel.setObjectName("svdVTLabel")
        self.verticalLayoutTab3.addWidget(self.svdVTLabel)
        self.svdVTTable = QtWidgets.QTableWidget(self.tabSVD)
        self.svdVTTable.setObjectName("svdVTTable")
        self.svdVTTable.setColumnCount(0)
        self.svdVTTable.setRowCount(0)
        self.verticalLayoutTab3.addWidget(self.svdVTTable)
        self.resultsTabs.addTab(self.tabSVD, "")
        self.verticalLayout.addWidget(self.resultsTabs)
        self.bottomButtonLayout = QtWidgets.QHBoxLayout()
        self.bottomButtonLayout.setObjectName("bottomButtonLayout")
        self.clearButton = QtWidgets.QPushButton(MatrixGui)
        self.clearButton.setObjectName("clearButton")
        self.bottomButtonLayout.addWidget(self.clearButton)
        self.exportButton = QtWidgets.QPushButton(MatrixGui)
        self.exportButton.setObjectName("exportButton")
        self.bottomButtonLayout.addWidget(self.exportButton)
        self.glossaryButton = QtWidgets.QPushButton(MatrixGui)
        self.glossaryButton.setObjectName("glossaryButton")
        self.bottomButtonLayout.addWidget(self.glossaryButton)
        self.verticalLayout.addLayout(self.bottomButtonLayout)

        self.retranslateUi(MatrixGui)
        QtCore.QMetaObject.connectSlotsByName(MatrixGui)

    def retranslateUi(self, MatrixGui):
        _translate = QtCore.QCoreApplication.translate
        MatrixGui.setWindowTitle(_translate("MatrixGui", "Matrix Diagonalization and Orthogonality Checker"))
        self.inputGroupBox.setTitle(_translate("MatrixGui", "Matrix Input"))
        self.labelRows.setText(_translate("MatrixGui", "Rows:"))
        self.labelCols.setText(_translate("MatrixGui", "Columns:"))
        self.computeButton.setText(_translate("MatrixGui", "Compute Diagonalization"))
        self.orthogonalityButton.setText(_translate("MatrixGui", "Check Orthogonality"))
        self.svdButton.setText(_translate("MatrixGui", "Compute SVD"))
        self.diagStatusLabel.setText(_translate("MatrixGui", "Diagonalization Status"))
        self.labelDiagMatrix.setText(_translate("MatrixGui", "Diagonalized Matrix:"))
        self.labelTransformMatrix.setText(_translate("MatrixGui", "Transformation Matrix:"))
        self.resultsTabs.setTabText(self.resultsTabs.indexOf(self.tabDiagonalization), _translate("MatrixGui", "Diagonalization Result"))
        self.orthoStatusLabel.setText(_translate("MatrixGui", "Orthogonality Status"))
        self.labelOrthoProduct.setText(_translate("MatrixGui", "Matrix × Transpose:"))
        self.resultsTabs.setTabText(self.resultsTabs.indexOf(self.tabOrthogonality), _translate("MatrixGui", "Orthogonality Check"))
        self.svdULabel.setText(_translate("MatrixGui", "Matrix U:"))
        self.svdSLabel.setText(_translate("MatrixGui", "Singular Values (S):"))
        self.svdVTLabel.setText(_translate("MatrixGui", "Matrix V^T:"))
        #self.resultsTabs.setTabText(self.resultsTabs.indexOf(self.tabSVD), _translate("MatrixGui", "SVD Result"))
        self.clearButton.setText(_translate("MatrixGui", "Clear"))
        self.exportButton.setText(_translate("MatrixGui", "Export Results"))
        self.glossaryButton.setText(_translate("MatrixGui", "Glossary"))

    def __main_test__(self):
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MatrixGui = QtWidgets.QWidget()
        ui = Ui_MatrixGui()
        ui.setupUi(MatrixGui)
        MatrixGui.show()
        sys.exit(app.exec_())
