doc_sources = [
  'cvxopt.inv',
  'cvxpy.inv',
  'cypari2.inv',
  'cysignals.inv',
  'flint.inv',
  'fpylll.inv',
  'gmpy2.inv',
  'ipykernel.inv',
  'ipython.inv',
  'ipywidgets.inv',
  'matplotlib.inv',
  'mpmath.inv',
  'networkx.inv',
  'numpy.inv',
  'pexpect.inv',
  'pplpy.inv',
  'ptyprocess.inv',
  'python.inv',
  'rpy2.inv',
  'scipy.inv',
  'sphinx.inv',
  'sympy.inv',
  'traitlets.inv',
]

foreach file : doc_sources
  doc_src += fs.copyfile(file)
endforeach
