project(
  'polytopes_db',
  version: '20170220.p0',
  meson_version: '>=1.5',
)

polytopes_db_data_dir = meson.current_source_dir()
polytopes_db_files = files(
  'reflexive_polytopes_2d',
  'reflexive_polytopes_3d',
  'Full2d/zzdb.info',
  'Full2d/zzdb.v03',
  'Full2d/zzdb.v04',
  'Full2d/zzdb.v05',
  'Full2d/zzdb.v06',
  'Full3d/zzdb.info',
  'Full3d/zzdb.v04',
  'Full3d/zzdb.v05',
  'Full3d/zzdb.v06',
  'Full3d/zzdb.v07',
  'Full3d/zzdb.v08',
  'Full3d/zzdb.v09',
  'Full3d/zzdb.v10',
  'Full3d/zzdb.v11',
  'Full3d/zzdb.v12',
  'Full3d/zzdb.v13',
)
