from typing import Any

from sage.rings.finite_rings.integer_mod import IntegerMod_abstract
from sage.rings.integer import Integer
from sage.rings.polynomial.polynomial_zmod_flint import Polynomial_zmod_flint

class Matrix_modn_dense_flint:
    def __init__(self, parent, entries=None, copy=None, coerce: bool = True) -> Any: ...
    def _solve_right_modn(self, B, check: bool = True) -> Any: ...
    def __cinit__(self, parent, *args, **kwds) -> Any: ...
    def pivots(self) -> tuple[int, ...]: ...
    def strong_echelon_form(self) -> Matrix_modn_dense_flint: ...
    def _richcmp_(self, right: Matrix_modn_dense_flint, op) -> bool: ...
    def hessenbergize(self) -> None: ...
    def _shift_mod(
        self, modulus, shift=1, mul: bool = True, domod: bool = True
    ) -> Matrix_modn_dense_flint: ...
    def __bool__(self) -> bool: ...
    def _sub_(self, _right: Matrix_modn_dense_flint) -> Matrix_modn_dense_flint: ...
    def transpose(self) -> Matrix_modn_dense_flint: ...
    def hessenberg_form(self) -> Matrix_modn_dense_flint: ...
    def __dealloc__(self) -> None: ...
    def trace(self) -> IntegerMod_abstract: ...
    def howell_form(self) -> Matrix_modn_dense_flint: ...
    def howellize(self, transformation=False) -> None: ...
    def rank(self) -> Integer: ...
    def strong_echelonize(self) -> None: ...
    def determinant(self, algorithm: str | None = None) -> IntegerMod_abstract: ...
    def _change_implementation(self, implementation) -> Any: ...
    def _matrices_from_rows(
        self, nrows: int, ncols: int
    ) -> list[Matrix_modn_dense_flint]: ...
    def inverse_of_unit(self, algorithm=None) -> Matrix_modn_dense_flint: ...
    def __invert__(self) -> Matrix_modn_dense_flint: ...
    def _right_kernel_matrix(
            self, algorithm: str | none = None, proof=None
    ) -> tuple[str, Matrix_modn_dense_flint]: ...
    def _lmul_(self, right) -> Matrix_modn_dense_flint: ...
    def __copy__(self) -> Matrix_modn_dense_flint: ...
    def echelonize(self, algorithm='default', **kwds) -> None: ...
    def _echelon_copy(self) -> Matrix_modn_dense_flint: ...
    def _pivots(self) -> tuple[tuple[int, ...], tuple[int, ...]]: ...
    def __pow__(self, n, dummy) -> Matrix_modn_dense_flint: ...
    def minpoly(
        self, var='x', algorithm='flint', proof=None
    ) -> Polynomial_zmod_flint: ...
    def charpoly(self, var='x', algorithm=None) -> Polynomial_zmod_flint: ...
    def _matrix_from_rows_of_matrices(X) -> Matrix_modn_dense_flint: ...
    def __neg__(self) -> Matrix_modn_dense_flint: ...
    def _add_(self, _right: Matrix_modn_dense_flint) -> Matrix_modn_dense_flint: ...

MAX_MODULUS: int = ...
