#!/usr/bin/env bash
if [ -z "$MESON_SOURCE_ROOT" -o -z "$MESON_DIST_ROOT" ]; then
    echo >&2 "$0: Should only be run by meson"
    exit 1
fi
set -ex
if [ -L "$MESON_DIST_ROOT"/doc -o ! -d "$MESON_DIST_ROOT"/doc ]; then
    # Remove symlink copied in by meson
    rm -f "$MESON_DIST_ROOT"/doc
    mkdir -p "$MESON_DIST_ROOT"/doc
    # Follow symlink
    (cd "$MESON_SOURCE_ROOT"/doc && tar -c -f - .) | (cd "$MESON_DIST_ROOT"/doc && tar -x -f - --no-same-permissions --no-acls --no-same-owner --no-xattrs)
fi
# Copy file generated by bootstrap (not in git)
cp "$MESON_SOURCE_ROOT"/pyproject.toml "$MESON_DIST_ROOT"/
# Remove m4 source
rm -f "$MESON_DIST_ROOT"/pyproject.toml.m4
