"""
Sergeev Superalgebras
"""
# ***************************************************************************
#  Copyright (C) 2026 Travis Scrimshaw <tcscrims at gmail.com>
#
#  Distributed under the terms of the GNU General Public License (GPL)
#                  https://www.gnu.org/licenses/
# ***************************************************************************

from sage.combinat.free_module import CombinatorialFreeModule_Tensor
from sage.data_structures.bitset import FrozenBitset
from sage.rings.integer_ring import ZZ
from sage.rings.rational_field import QQ
from sage.misc.cachefunc import cached_method

class SergeevSuperalgebra(CombinatorialFreeModule_Tensor):
    r"""
    The Sergeev superalgebra.

    Let `R` be a commutative ring. The *Sergeev superalgebra* is
    the superalgebra on the superspace `R[S_n] \otimes_R C_n`, where
    `C_n` denotes the Clifford algebra over `R` with generators
    `c_1, \ldots, c_n` satisfying `c_i^2 = a` and `c_i c_j = -c_j c_i`
    for `i \neq j`, with twisted multiplication

    .. MATH::

        (\sigma \otimes \phi) (\tau \otimes \psi)
        = (\sigma \tau) \otimes \tau^{-1}(\phi)\psi,

    where `S_n` acts naturally on `C_n \conj \bigwedge R^n` (as
    `R`-modules) by permuting indices. The superalgebra structure is
    inherited by that of `C_n` with `\deg c_i = 1` and `\deg S_n = 0`.

    There is an analog of Schur-Weyl duality [Sergeev1985]_ for the
    Sergeev superalgebra, which is known as *Sergeev duality*. Let
    `V = \CC^{n|n}` be the super vector space of (super)dimension `n|n`
    (that is, `2n` dimensional when forgetting about the `\ZZ/2\ZZ`-grading
    and each graded component is `n` dimensional), and consider
    `V^{\otimes k}`. Then the Sergeev superalgebra `S_k` with `a = -1`
    acts on the right by (signed) graded place permutation

    .. MATH::

        (w_1 \otimes \cdots \otimes w_k) \cdot \sigma_j
        = (-1)^{|w_j| |w_{j+1}|} w_1 \otimes \cdots \otimes w_{j+1}
        \otimes w_j \otimes \cdots \otimes w_k,

    where `\sigma_j = (j \; j+1)` is a simple transposition, and the
    Clifford algebra generators act by

    .. MATH::

        (w_1 \otimes \cdots \otimes w_k) \cdot \sigma_j
        = (-1)^{|w_1| + \cdots + |w_{j-1}|} w_1 \otimes \cdots \otimes P(w_j)
        \otimes \cdots \otimes w_k,

    where for the basis vectors of `\CC^{m|n}` we define the odd operator
    `P(e_b) := (-1)^{\abs{b}+1} e_{\overline{b}}` for all `b = 1, \ldots, n,
    \overline{1}, \ldots, \overline{n}` (with `\overline{\overline{b}} = b`).
    This centralizes the natural Lie superalgebra `\mathfrak{q}_n` action
    by realizing `V` as its natural represenation under the block matrix
    action `\begin{pmatrix} A & B \\ B & A \end{pmatrix}`, where `A, B` are
    `n \times n` matrices.

    A noteworthy subalgebra of the Sergeev subalgebra is given by the
    decomposition as superalgebras `S_k = A_k \otimes C_k`, where `A_k`
    is generated by the elements

    .. MATH::

        \tau_{i,j} = (c_i - c_) \sigma_{i,j},

    where `\sigma_{i,j} = (i \; j)` is the transposition swapping `i` and `j`.
    (See, e.g., :arxiv:`math/9810148` with rescaling the generators by
    `(\sqrt{2}a)^{-1}`.) In particular, this decomposition means that `A_k`
    supercommutes with all Clifford algebra generators. The relations satisfy

    .. MATH::

        \begin{gathered}
        \tau_{i,j} = -\tau_{j,i}, \qquad \tau_{i,j}^2 = -2a,
        \\
        \tau_{i,j} \tau_{k,l} = -\tau_{k,l} \tau_{i,j} \quad
        \text{ if } \{i, j\} \cap \{k, l\} = \emptyset,
        \\
        \tau_{i,j} \tau_{j,k} \tau_{i,j} = \tau_{j,k} \tau_{i,j} \tau_{j,k}
        = 2a\tau_{i,k}.
        \end{gathered}

    INPUT:

    - ``n`` -- the rank
    - ``a`` -- (default: `1 \in \QQ`) the parameter `a`
    - ``base_ring`` -- (default: parent of ``a``) base ring of
      characteristic not equal to 2

    EXAMPLES:

    We will construct the Sergeev duality for `n = k = 2`. We first
    implement the action of the generators as moprhisms::

        sage: n = 2
        sage: S = algebras.Sergeev(n, -1, QQ)
        sage: S
        Sergeev Superalgebra of rank 2 with a=-1 over Rational Field
        sage: s1,c1,c2 = S.algebra_generators()
        sage: c1^2
        -1#[1, 2]
        sage: indices = list(range(1,n+1)) + [-i for i in range(1,n+1)]
        sage: V = CombinatorialFreeModule(QQ, indices)
        sage: T = tensor([V, V])
        sage: S1 = T.module_morphism(lambda x: (-1)^bool(x[0] < 0 and x[1] < 0)
        ....:                        * T.basis()[x[1],x[0]], codomain=T)
        sage: C1 = T.module_morphism(lambda x: (-1)^bool(x[0] > 0)
        ....:                        * T.basis()[-x[0],x[1]], codomain=T)
        sage: C2 = T.module_morphism(lambda x: (-1)^(bool(x[0] < 0) + bool(x[1] > 0))
        ....:                        * T.basis()[x[0],-x[1]], codomain=T)
        sage: [(b, S1(b), C1(b), C2(b)) for b in T.basis()]
        [(B[1] # B[1],    B[1] # B[1],   -B[-1] # B[1],  -B[1] # B[-1]),
         (B[1] # B[2],    B[2] # B[1],   -B[-1] # B[2],  -B[1] # B[-2]),
         (B[1] # B[-1],   B[-1] # B[1],  -B[-1] # B[-1],  B[1] # B[1]),
         (B[1] # B[-2],   B[-2] # B[1],  -B[-1] # B[-2],  B[1] # B[2]),
         (B[2] # B[1],    B[1] # B[2],   -B[-2] # B[1],  -B[2] # B[-1]),
         (B[2] # B[2],    B[2] # B[2],   -B[-2] # B[2],  -B[2] # B[-2]),
         (B[2] # B[-1],   B[-1] # B[2],  -B[-2] # B[-1],  B[2] # B[1]),
         (B[2] # B[-2],   B[-2] # B[2],  -B[-2] # B[-2],  B[2] # B[2]),
         (B[-1] # B[1],   B[1] # B[-1],   B[1] # B[1],    B[-1] # B[-1]),
         (B[-1] # B[2],   B[2] # B[-1],   B[1] # B[2],    B[-1] # B[-2]),
         (B[-1] # B[-1], -B[-1] # B[-1],  B[1] # B[-1],  -B[-1] # B[1]),
         (B[-1] # B[-2], -B[-2] # B[-1],  B[1] # B[-2],  -B[-1] # B[2]),
         (B[-2] # B[1],   B[1] # B[-2],   B[2] # B[1],    B[-2] # B[-1]),
         (B[-2] # B[2],   B[2] # B[-2],   B[2] # B[2],    B[-2] # B[-2]),
         (B[-2] # B[-1], -B[-1] # B[-2],  B[2] # B[-1],  -B[-2] # B[1]),
         (B[-2] # B[-2], -B[-2] # B[-2],  B[2] # B[-2],  -B[-2] # B[2])]

    We verify the Sergeev algebra relations (in terms of matrices)::

        sage: S1M = S1.matrix()
        sage: C1M = C1.matrix()
        sage: C2M = C2.matrix()
        sage: C1M * C2M + C2M * C1M == 0
        True
        sage: C1M * S1M == S1M * C2M
        True
        sage: C2M * S1M == S1M * C1M
        True
        sage: C1M^2 == -1
        True
        sage: C2M^2 == -1
        True
        sage: S1M^2 == 1
        True

    We construct the action of the Lie superalgebra `\mathfrak{q}_n`
    on `V^{\otimes n}` given by its basis indices::

        sage: from itertools import product
        sage: q2basis = list(product(*[range(2), range(1,n+1), range(1,n+1)]))
        sage: q2basis
        [(0, 1, 1), (0, 1, 2), (0, 2, 1), (0, 2, 2),
         (1, 1, 1), (1, 1, 2), (1, 2, 1), (1, 2, 2)]

        sage: def q2Vact(qb, i):  # action on V
        ....:     coeff = 1
        ....:     if qb[0] == 1:
        ....:         qb = [1, qb[1], -qb[2]]
        ....:     if qb[2] == i:
        ....:         return V.monomial(qb[1])
        ....:     if qb[2] == -i:
        ....:         return V.monomial(-qb[1])
        ....:     return V.zero()
        sage: [(qb, [q2Vact(qb, i) for i in V.basis().keys()]) for qb in q2basis]
        [((0, 1, 1), [B[1], 0, B[-1], 0]),
         ((0, 1, 2), [0, B[1], 0, B[-1]]),
         ((0, 2, 1), [B[2], 0, B[-2], 0]),
         ((0, 2, 2), [0, B[2], 0, B[-2]]),
         ((1, 1, 1), [B[-1], 0, B[1], 0]),
         ((1, 1, 2), [0, B[-1], 0, B[1]]),
         ((1, 2, 1), [B[-2], 0, B[2], 0]),
         ((1, 2, 2), [0, B[-2], 0, B[2]])]

        sage: def q2Tact(qb, x):
        ....:     return (tensor([q2Vact(qb, x[0]), V.monomial(x[1])])
        ....:             + (-1)^(qb[0]*bool(x[0]<0)) * tensor([V.monomial(x[0]), q2Vact(qb, x[1])]))
        sage: [q2Tact(q2basis[0], x) for x in T.basis().keys()]
        [2*B[1] # B[1], B[1] # B[2], 2*B[1] # B[-1], B[1] # B[-2], B[2] # B[1],
         0, B[2] # B[-1], 0, 2*B[-1] # B[1], B[-1] # B[2], 2*B[-1] # B[-1],
         B[-1] # B[-2], B[-2] # B[1], 0, B[-2] # B[-1], 0]
        sage: [q2Tact(q2basis[4], x) for x in T.basis().keys()]
        [B[-1] # B[1] + B[1] # B[-1], B[-1] # B[2], B[-1] # B[-1] + B[1] # B[1],
         B[-1] # B[-2], B[2] # B[-1], 0, B[2] # B[1], 0,
         -B[-1] # B[-1] + B[1] # B[1], B[1] # B[2], -B[-1] # B[1] + B[1] # B[-1],
         B[1] # B[-2], -B[-2] # B[-1], 0, -B[-2] # B[1], 0]

    We verify the supercommuting action::

        sage: q2maps = [T.module_morphism(lambda x,q=qb: q2Tact(q, x), codomain=T)
        ....:           for qb in q2basis]
        sage: all(S1(g(b)) == g(S1(b)) for b in T.basis() for g in q2maps)
        True
        sage: all(C1(g(b)) == (-1)^bool(i>3) * g(C1(b)) for b in T.basis()
        ....:     for i,g in enumerate(q2maps))
        True
        sage: all(C2(g(b)) == (-1)^bool(i>3) * g(C2(b)) for b in T.basis()
        ....:     for i,g in enumerate(q2maps))
        True

    We construct the generators `\tau_{i,j}` of the subalgebra `A_3` and
    verify the corresponding relations and properties::

        sage: R.<a> = QQ[]
        sage: S = algebras.Sergeev(4, a)
        sage: s1, s2, s3, c1, c2, c3, c4 = S.algebra_generators()
        sage: t12 = (c1 - c2) * s1
        sage: t13 = (c1 - c3) * s2*s1*s2
        sage: t14 = (c1 - c4) * s3*s2*s1*s2*s3
        sage: t23 = (c2 - c3) * s2
        sage: t24 = (c2 - c4) * s3*s2*s3
        sage: t34 = (c3 - c4) * s3
        sage: T = [t12, t13, t14, t23, t24, t34]; T
        [c1#[2, 1, 3, 4] - c2#[2, 1, 3, 4],
         c1#[3, 2, 1, 4] - c3#[3, 2, 1, 4],
         c1#[4, 2, 3, 1] - c4#[4, 2, 3, 1],
         c2#[1, 3, 2, 4] - c3#[1, 3, 2, 4],
         c2#[1, 4, 3, 2] - c4#[1, 4, 3, 2],
         c3#[1, 2, 4, 3] - c4#[1, 2, 4, 3]]
        sage: t12 * t34 == -t34 * t12
        True
        sage: t12 * t23 * t12 == 2*a*t13
        True
        sage: t23 * t12 * t23 == 2*a*t13
        True
        sage: t23 * t24 * t23 == 2*a*t34
        True
        sage: t24 * t23 * t24 == -2*a*t34
        True
        sage: all(t^2 == -2*a for t in T)
        True
        sage: all(t * c == -c * t for t in T for c in [c1,c2,c3,c4])
        True
    """
    @staticmethod
    def __classcall_private__(cls, n, a=QQ.one(), base_ring=None):
        r"""
        Normalize input to ensure a unique representation.

        EXAMPLES::

            sage: R.<a> = PolynomialRing(QQ)
            sage: S1 = algebras.Sergeev(3, a)
            sage: S2 = algebras.Sergeev(3, 'a', R)
            sage: S1 is S2
            True

            sage: algebras.Sergeev(3, GF(2).one())
            Traceback (most recent call last):
            ...
            ValueError: the base ring cannot have characteristic 2
        """
        if base_ring is None:
            base_ring = a.parent()
        a = base_ring(a)
        n = ZZ(n)
        if base_ring.one() + base_ring.one() == base_ring.zero():
            raise ValueError("the base ring cannot have characteristic 2")
        return super().__classcall__(cls, n, a, base_ring)

    def __init__(self, n, a, base_ring):
        r"""
        Initialize ``self``.

        EXAMPLES::

            sage: R.<a> = PolynomialRing(QQ)
            sage: S = algebras.Sergeev(3, a)
            sage: TestSuite(S).run(elements=list(S.basis()))

            sage: S = algebras.Sergeev(3, GF(5)(4))
            sage: TestSuite(S).run(elements=list(S.basis()))
        """
        from sage.matrix.constructor import matrix
        from sage.combinat.symmetric_group_algebra import SymmetricGroupAlgebra
        from sage.quadratic_forms.quadratic_form import QuadraticForm
        from sage.algebras.clifford_algebra import CliffordAlgebra
        from sage.categories.algebras_with_basis import AlgebrasWithBasis
        self._SGA = SymmetricGroupAlgebra(base_ring, n)
        Q = QuadraticForm(2 * a * matrix.identity(base_ring, n))
        names = tuple([f'c{i}' for i in range(1, n+1)])
        self._C = CliffordAlgebra(Q, names=names)
        self._n = n
        self._a = a
        Cat = AlgebrasWithBasis(base_ring).Super()
        CombinatorialFreeModule_Tensor.__init__(self, (self._C, self._SGA),
                                                category=Cat, tensor_symbol='#')

    def _repr_(self) -> str:
        r"""
        EXAMPLES::

            sage: algebras.Sergeev(4, QQ(5))
            Sergeev Superalgebra of rank 4 with a=5 over Rational Field
        """
        return "Sergeev Superalgebra of rank {} with a={} over {}".format(
                self._n, self._a, self.base_ring())

    @cached_method
    def one_basis(self):
        r"""
        Return the basis element indexing the multiplicative identity
        in ``self``.

        EXAMPLES::

            sage: S = algebras.Sergeev(4, QQ(5))
            sage: S.one_basis()
            (0, [1, 2, 3, 4])
        """
        return (self._C.one_basis(), self._SGA.one_basis())

    @cached_method
    def algebra_generators(self):
        """
        Return the algebra generators of ``self``.

        EXAMPLES::

            sage: S = algebras.Sergeev(3, polygen(GF(5), 'a'))
            sage: list(S.algebra_generators())
            [1#[2, 1, 3], 1#[1, 3, 2], c1#[1, 2, 3], c2#[1, 2, 3], c3#[1, 2, 3]]
        """
        from sage.sets.family import Family
        one = self._C.one_basis()
        data = {i: self.monomial((one, s))
                for i, s in self._SGA.indices().simple_reflections().items()}
        one = self._SGA.one_basis()
        data.update({key: self.monomial((g.leading_support(), one))
                for key, g in self._C.algebra_generators().items()})
        return Family(data)

    @cached_method
    def product_on_basis(self, A, B):
        r"""
        Return the product of basis elements indexed by ``A`` and ``B``.

        EXAMPLES::

            sage: R.<a> = PolynomialRing(QQ)
            sage: S = algebras.Sergeev(3, a)
            sage: elt = sum(S.algebra_generators())
            sage: elt^2
            (3*a+2)*1#[1, 2, 3] + 1#[2, 3, 1] + 1#[3, 1, 2] + 2*c2#[2, 1, 3]
             + 2*c1#[2, 1, 3] + 2*c3#[1, 3, 2] + 2*c3#[2, 1, 3]
             + 2*c1#[1, 3, 2] + 2*c2#[1, 3, 2]

        We check some cases for associativity::

            sage: s1,s2,c1,c2,c3 = S.algebra_generators()
            sage: s2 * (s1 * c1)
            c3#[3, 1, 2]
            sage: (s2 * s1) * c1
            c3#[3, 1, 2]
            sage: c2 * (s2 * (c2*c3))
            -a*c3#[1, 3, 2]
            sage: (c2 * s2) * (c2*c3)
            -a*c3#[1, 3, 2]
            sage: (s1 * s2 * s1) * (c1*c2*c3)
            -c1*c2*c3#[3, 2, 1]
            sage: s1 * (s2 * (s1 * (c1*c2*c3)))
            -c1*c2*c3#[3, 2, 1]
        """
        ml, sigma = A
        mr, tau = B

        from sage.combinat.permutation_cython import left_action_same_n
        S = self._SGA.indices()
        sigma = list(sigma)
        st = S(left_action_same_n(sigma, list(tau)))

        if mr.isempty():
            return self.monomial((ml, st))
        mr = [sigma[i]-1 for i in mr]

        t = list(ml)
        coeff = self.base_ring().one()

        tot_cross = 0
        for j in mr:
            for ind in range(len(t)-1, -1, -1):
                if t[ind] > j:
                    tot_cross += 1
                    continue
                if t[ind] == j:
                    coeff *= self._a
                    t.pop(ind)
                    break
                # otherwise t[ind] < j:
                t.insert(ind+1, j)
                break
            else:
                t.insert(0, j)

        if tot_cross % 2:
            coeff = -coeff

        if not t:
            t = FrozenBitset(None)
        else:
            t = FrozenBitset(t)
        return self.term((t, st), coeff)

    def degree_on_basis(self, A):
        r"""
        Return the degree of the basis element indexed by ``A``.

        EXAMPLES::

            sage: S = algebras.Sergeev(3, QQ(5))
            sage: [S.degree_on_basis(g.leading_support()) for g in S.algebra_generators()]
            [0, 0, 1, 1, 1]

            sage: s1,s2,c1,c2,c3 = S.algebra_generators()
            sage: (c1 * c2 * c3).degree()  # indirect doctest
            1
            sage: (c3 * c1 * c2 * c3).degree()  # indirect doctest
            0
        """
        return ZZ(len(A[0]) % 2)

