from typing import Any

class ParentWithBase:
    def __init__(self, base: Any, *args: Any, **kwds: Any) -> None: ...
    def _coerce_c_impl(self, x: Any) -> Any: ...
    def base_extend(self, X: Any) -> Any: ...

def check_old_coerce(p: Any) -> None: ...
